package com.bobona.apri.input;

import com.bobona.apri.utils.Config;
import com.bobona.apri.utils.Vector2;

public interface Keyboard {

    // ignore capital
    Keyboard o = Config.instantiate(Config.KEYBOARD_CLASS);

    boolean isKeyPressed(int key);
    boolean isKeyJustPressed(int key);
    Vector2 getMousePos();
    float getMouseX();
    float getMouseY();
    int keycode(Key key);
    Key key(int keycode);

    enum Key {
        ANY_KEY,
        NUM_0,
        NUM_1,
        NUM_2,
        NUM_3,
        NUM_4,
        NUM_5,
        NUM_6,
        NUM_7,
        NUM_8,
        NUM_9,
        A,
        ALT_LEFT,
        ALT_RIGHT,
        APOSTROPHE,
        AT,
        B,
        BACK,
        BACKSLASH,
        C,
        CALL,
        CAMERA,
        CLEAR,
        COMMA,
        D,
        DEL,
        BACKSPACE,
        FORWARD_DEL,
        DPAD_CENTER,
        DPAD_DOWN,
        DPAD_LEFT,
        DPAD_RIGHT,
        DPAD_UP,
        CENTER,
        DOWN,
        LEFT,
        RIGHT,
        UP,
        E,
        ENDCALL,
        ENTER,
        ENVELOPE,
        EQUALS,
        EXPLORER,
        F,
        FOCUS,
        G,
        GRAVE,
        H,
        HEADSETHOOK,
        HOME,
        I,
        J,
        K,
        L,
        LEFT_BRACKET,
        M,
        MEDIA_FAST_FORWARD,
        MEDIA_NEXT,
        MEDIA_PLAY_PAUSE,
        MEDIA_PREVIOUS,
        MEDIA_REWIND,
        MEDIA_STOP,
        MENU,
        MINUS,
        MUTE,
        N,
        NOTIFICATION,
        NUM,
        O,
        P,
        PERIOD,
        PLUS,
        POUND,
        POWER,
        Q,
        R,
        RIGHT_BRACKET,
        S,
        SEARCH,
        SEMICOLON,
        SHIFT_LEFT,
        SHIFT_RIGHT,
        SLASH,
        SOFT_LEFT,
        SOFT_RIGHT,
        SPACE,
        STAR,
        SYM,
        T,
        TAB,
        U,
        UNKNOWN,
        V,
        VOLUME_DOWN,
        VOLUME_UP,
        W,
        X,
        Y,
        Z,
        META_ALT_LEFT_ON,
        META_ALT_ON,
        META_ALT_RIGHT_ON,
        META_SHIFT_LEFT_ON,
        META_SHIFT_ON,
        META_SHIFT_RIGHT_ON,
        META_SYM_ON,
        CONTROL_LEFT,
        CONTROL_RIGHT,
        ESCAPE,
        END,
        INSERT,
        PAGE_UP,
        PAGE_DOWN,
        PICTSYMBOLS,
        SWITCH_CHARSET,
        BUTTON_CIRCLE,
        BUTTON_A,
        BUTTON_B,
        BUTTON_C,
        BUTTON_X,
        BUTTON_Y,
        BUTTON_Z,
        BUTTON_L1,
        BUTTON_R1,
        BUTTON_L2,
        BUTTON_R2,
        BUTTON_THUMBL,
        BUTTON_THUMBR,
        BUTTON_START,
        BUTTON_SELECT,
        BUTTON_MODE,
        NUMPAD_0,
        NUMPAD_1,
        NUMPAD_2,
        NUMPAD_3,
        NUMPAD_4,
        NUMPAD_5,
        NUMPAD_6,
        NUMPAD_7,
        NUMPAD_8,
        NUMPAD_9,
        COLON,
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
    }
}
